[package]
name = "liveprobe-bpf-loader"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
libbpf-rs.workspace = true
libc.workspace = true
nix.workspace = true
object.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
liveprobe-native-protocol = { path = "../protocol" }

[build-dependencies]
object.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
